### ISSUE TITLE
Axios Cross-Site Request Forgery Vulnerability

### ISSUE THREAD

**Issue by sam-trost** [cohere-ai/cohere-typescript#107]
An issue discovered in Axios 0.8.1 through 1.5.1 inadvertently reveals the confidential XSRF-TOKEN stored in cookies by including it in the HTTP header X-XSRF-TOKEN for every request made to any host allowing attackers to view sensitive information.

Dependabot has also flagged it in this repository.

https://github.com/cohere-ai/cohere-typescript/pull/101

**Comment by billytrend-cohere** [comment]
Hey Sam, thanks for reporting this. The dependency is now updated as part of 2.5.0. We will try to improve the speed at which we bump these dependencies!

**Comment by billytrend-cohere** [comment]
This fixed now in 7.6.1, we're now using fetch, not axios! Cheers
