### ISSUE TITLE
7.6.1 Error: Body already used

### ISSUE THREAD

**Issue by shabegom** [cohere-ai/cohere-typescript#108]
Hello! I believe in the switch from axios to fetch in 7.6.1 an error was introduced:

4 |  */
5 | Object.defineProperty(exports, "__esModule", { value: true });
6 | exports.CohereError = void 0;
7 | class CohereError extends Error {
8 |     constructor({ message, statusCode, body }) {
9 |         super(buildMessage({ message, statusCode, body }));
            ^
error: Body already used
      at new CohereError (.../node_modules/cohere-ai/errors/CohereError.js:9:8)
      at .../node_modules/cohere-ai/Client.js:330:26
      at fulfilled (.../node_modules/cohere-ai/Client.js:31:47)

Reverting to 7.6.0 seems to resolve this issue,

**Comment by dsinghvi** [comment]
@shabegom thanks for reporting the error, we are diving in right now. Any chance you can share a snippet of code that reproduced this issue?

**Comment by shabegom** [comment]
Sure thing @dsinghvi . I hope this isn't a "me" problem. This is my first attempt at using Cohere's rerank and I've inserted it into an existing langchain RunnableSequence.

This return the error on 7.6.1:

```js
  const combineDocumentsChain = RunnableSequence.from([
      context: async (output: string) => {

       // Retrieving Docs from supabase vector store
        const relevantDocs = await retriever.getRelevantDocuments(output);

       // converting the objects to proper format for cohere rerank
        const docsForRerank = relevantDocs.map(doc => ({text: doc.pageContent}))

      // sending to cohere. This is where the error seems to happen.
        const rerank = await cohere.rerank({documents: docsForRerank, query: output})

     // creating the final object, filtering and sorting
        const rerankedWithMetadata = relevantDocs.map((doc, i) => {
          return {
            pageContent: doc.pageContent,
            metadata: doc.metadata,
            rank: rerank.results[i].index
          }
        }).filter(doc => doc.rank <= 5).sort((a,b) => a.rank - b.rank)
        const string = JSON.stringify(rerankedWithMetadata)
        return string
      },
    },
    combineDocumentsPrompt,
    gpt4,
    new StringOutputParser(),
  ]);
```

It doesn't return the error in 7.6.0 which is why I assumed it had to do with moving from axios to fetch. Apologies if that is a wrong assumption.

**Comment by dsinghvi** [comment]
@shabegom -- didn't see your response till now, will take a look now. Our hunch is that it has to do with calling `response.text()` after `response.body()` in this line: https://github.com/cohere-ai/cohere-typescript/blob/c2eceb4a845098240ba0bc44e3787ccf75e268e8/src/core/fetcher/Fetcher.ts#L131

**Comment by billytrend-cohere** [comment]
@dsinghvi yeah interesting, I can repro the issue with this code. We should be returning valid json though so that is a further question!

```
(async () => {
    const notJson = await fetch("https://example.com")
    try {
        await notJson.json()
    } catch (e) {
        await notJson.text()
    }  
})()
```

**Comment by dsinghvi** [comment]
@billytrend-cohere this is now fixed in the latest TypeScript generator https://github.com/fern-api/fern-typescript/pull/671

**Comment by billytrend-cohere** [comment]
Thanks @dsinghvi , I've release 7.7.4 which should have the fix for you @shabegom
