### ISSUE TITLE
generate does not support stream

### ISSUE THREAD

**Issue by Goldziher** [cohere-ai/cohere-typescript#111]
Hi,

the client.generate method currently does not support `stream: true`. The typing is for a single response, non-iterable, and the code also doesnt appear to support streaming.

**Comment by dsinghvi** [comment]
@Goldziher thanks for filing this issue. It looks like the issue here may be related to some missing configuration in the OpenAPI spec. Tagging @billytrend-cohere who may have some more insight into when this will be added to the spec!

**Comment by billytrend-cohere** [comment]
Hey both, we need to make a backend change before the sdk can support streaming because currently the events do not form a discriminated union. Will come back with updates asap!

**Comment by billytrend-cohere** [comment]
Hey, glad you found a work around, we are limited in how the auto-generated sdks can model the events so will need to make a backend change for their sake.

**Comment by billytrend-cohere** [comment]
Hey @Goldziher this should work in 7.7.1 as follows. Thanks again!

```
    const cohere = new CohereClient({
        token: "gJG6KYLmIcmVHElpX5JYiOQxIQyZ23DSN76EZPEr",
    });

    const str = await cohere.generateStream({
        prompt: "Cohere is ",
    });

    for await (const chat of str) {
        if (chat.eventType === "text-generation") {
            process.stdout.write(chat.text);
        }
    }
```

**Comment by billytrend-cohere** [comment]
Hey @Goldziher this should work in 7.7.1 as follows. Thanks again!

```
    const cohere = new CohereClient({
        token: "xxx",
    });

    const str = await cohere.generateStream({
        prompt: "Cohere is ",
    });

    for await (const chat of str) {
        if (chat.eventType === "text-generation") {
            process.stdout.write(chat.text);
        }
    }
```

**Comment by Goldziher** [comment]
thanks, ill test!
