### ISSUE TITLE
Mutating `global.fetch` causes issues with other libraries

### ISSUE THREAD

**Issue by wilsonzlin** [cohere-ai/cohere-typescript#113]
It appears that this library [changes `global.fetch`](https://github.com/cohere-ai/cohere-typescript/blob/c2eceb4a845098240ba0bc44e3787ccf75e268e8/src/core/fetcher/Fetcher.ts#L6) if the global `fetch` does not exist. This causes issues with some other libraries that try to do the same thing, and also overrides the builtin `fetch` now available in Node.js; in general, mutating globals from a library is not ideal. For example, this caused all fetch calls from the Oracle Cloud SDK to fail, which I have also raised an [issue](https://github.com/oracle/oci-typescript-sdk/issues/259) for. As a side note, it also assumes that the platform is Node.js.

Might I suggest using [fetch-ponyfill](https://github.com/qubyte/fetch-ponyfill), which provides the same cross-browser fetch polyfill but doesn't mutate the global fetch function? It requires an import, but this should be trivial to migrate to as I found only [one call](https://github.com/search?q=repo%3Acohere-ai%2Fcohere-typescript%20fetch%28&type=code) to `fetch` in this library. Alternatively, perhaps create a local variable like `const fetchFn = typeof fetch == "function" ? fetch : require("node-fetch")` and use `fetchFn` instead of mutating `global.fetch`.

**Comment by dsinghvi** [comment]
@wilsonzlin thanks for the issue -- Cohere uses [Fern](https://buildwithfern.com/) to generate their SDKs and we'll be making a change to our generator to fix this!

**Comment by hoantran-it** [comment]
I've encountered the same issue with global node-fetch after many hours of debugging. @dsinghvi how can this issue be completely resolved? Thank you!

**Comment by billytrend-cohere** [comment]
Hey both, this issues should be resolved in 7.7.4 please let me know if it doesn't fix!

**Comment by hoantran-it** [comment]
> Hey both, this issues should be resolved in 7.7.4 please let me know if it doesn't fix!

API doesn't work anymore, returns empty when retrieving with `for await (const chat of stream) `

<img width="594" alt="Screenshot 2024-02-01 at 12 48 36" src="https://github.com/cohere-ai/cohere-typescript/assets/13161875/818d8928-9727-49e8-ba5c-7ca1dc96f26d">

**Comment by billytrend-cohere** [comment]
Hey @hoantran-it super grateful to you for reporting this. We p0'd a fix and 7.7.5 should now be good. We are going to add e2e testing to improve stability of this. Thanks for all of your patience.

**Comment by hoantran-it** [comment]
> Hey @hoantran-it super grateful to you for reporting this. We p0'd a fix and 7.7.5 should now be good. We are going to add e2e testing to improve stability of this. Thanks for all of your patience.

@billytrend-cohere thank you! It works well now 🥳
