### ISSUE TITLE
generateStream does not include finishReason

### ISSUE THREAD

**Issue by Goldziher** [cohere-ai/cohere-typescript#114]
Hi, the new `generateStream` is missing data i rely on:

```typescript
	finish_reason?:
		| 'COMPLETE'
		| 'MAX_TOKENS'
		| 'ERROR'
		| 'ERROR_TOXIC';
```

**Comment by billytrend-cohere** [comment]
Hey, can you help me understand your issue better? Finish reason should be defined here:

https://github.com/cohere-ai/cohere-typescript/blob/22819d93cfe8be2d453b2f82d6fa831078988084/src/api/types/GenerateStreamEnd.ts#L9

The following code prints `COMPLETE` for me:

```
    const str = await cohere.generateStream({
        prompt: "Cohere is ",
    });

    for await (const chat of str) {
        if (chat.eventType === "stream-end") {
            console.log(chat.finishReason!);
        }
    }
```

**Comment by Goldziher** [comment]
Lemme see again. Perhaps it's just a case of missing types, or a brain fart on my end.

**Comment by Goldziher** [comment]
> I think i might have found it! try 7.7.3 ?
> 
> https://github.com/cohere-ai/cohere-typescript/commit/c7d02986e6e4378d431ae19df1bf96b3388f7d1d#diff-294d64b732aea376d1e841a92a14e36646b157f84398779e0021389882864979R13

Will do

**Comment by Goldziher** [comment]
nope, this is not included in the typing. In v7.7.3 I see this in the typing:

```typescript
export interface GenerateStreamText extends Cohere.GenerateStreamEvent {
    /** A segment of text of the generation. */
    text: string;
    /** Refers to the nth generation. Only present when `num_generations` is greater than zero, and only when text responses are being streamed. */
    index?: number;
    isFinished: boolean;
}
```

**Comment by billytrend-cohere** [comment]
Hey, I took a look at the backend, and this "text-generation" event doesn't contain a finishReason because this event is never a finish event (isFinished will always be false). Can you share your code snippet so i can suggest changes? Thanks :)

**Comment by billytrend-cohere** [comment]
Hey, hope you managed to find a fix for this. The recommended way to get this field is the one here https://github.com/cohere-ai/cohere-typescript/issues/114#issuecomment-1898191541 . Please feel free to reopen the issue if you have further problems. Thanks!
