### ISSUE TITLE
Issues using sdk in next js server actions

### ISSUE THREAD

**Issue by billytrend-cohere** [cohere-ai/cohere-typescript#134]
A user reported

> so i was using cohere ai latest version in next js server actions - latest version - nvm 20 and 21.  I kept getting regular cohere errors about fetch missing.  The call would fail due to this- but not everytime.  Eventually i pnpm node fetch and included it as global at the top of the action to make it stop - hasnt shown up since.
> I tried node 20 and 21 - didnt make a difference

They will follow up with a snippet + sdk version

**Comment by RobertHH-IS** [comment]
node -v  v20.11.0 or node v21.5.0
"next": "^14.0.4",
"react": "18.2.0",

In server action with "use server"

  const rerank = await Cohere.rerank({
    documents: result.map((doc) => ({ text: doc.chunk })),
    query: query,
    model: "rerank-multilingual-v2.0",
    topN: 5,
  });

Although it would not error every time, it would error with regularity that it could not find fetch.

Eventually i pnpm i node-fetch   "node-fetch": "^3.3.2",
And added the following top of that file - 

import fetch from "node-fetch";
(global as any).fetch = fetch;

Never saw the error again.

Didn´t seem like it was the same issue with the embed.  I do not import it in that file.
queryEmbedding = await Cohere.embed({
        texts: [query],
        model: "embed-multilingual-v3.0",
        inputType: "search_query",
      });

**Comment by billytrend-cohere** [comment]
Hey, thanks for these details! Glad you found a fix. One thing I would mention is that there is a small risk this fix might affect other libraries in case you see weird behaviour from them any time.

Please could you try updating your sdk to the latest version  cohere-ai@7.7.5? Our vendor did some fixes to the fetch implementation since that version which I think will fix your use case cc @dsinghvi 

https://github.com/cohere-ai/cohere-typescript/compare/7.6.2...main#diff-44db24fb92214331d3845e557c568eef257639cffaea46901778da833209ef3a

**Comment by billytrend-cohere** [comment]
@dsinghvi flagged to me that the improvements here https://github.com/fern-api/fern/pull/2989 will also improve fetch robustness and we will release these updates too shortly

**Comment by RobertHH-IS** [comment]
Correct on it not being an optimal fix - just the fastest way to get it to "it seems to be working" state on dev.
Updated the package and removed that node-fetch stuff - no errors yet - so looks fixed!
