### ISSUE TITLE
No license in project

### ISSUE THREAD

**Issue by peterwoodworth** [cohere-ai/cohere-typescript#143]
Hi cohere team,

I noticed that the MIT license that was added to this repo was removed in the v7 release https://github.com/cohere-ai/cohere-typescript/commit/8a79b225a10433aaaf321de625ffe65fc11c58c4#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

Was this intentional? It would be helpful for me if there was a license on this project 🙂

**Comment by billytrend-cohere** [comment]
This is an omission! thanks for flagging. I will make sure that's restored asap

**Comment by billytrend-cohere** [comment]
No problem. It's restored now. If you're blocked and need me to release a npm package with the license in it then give me a shout but otherwise it will go out with the next release! Let me know if you have any more problems
