### ISSUE TITLE
Reading from "node:stream" is not handled by plugins

### ISSUE THREAD

**Issue by crtnx** [cohere-ai/cohere-typescript#156]
cohere-ai version: 7.10.0
next.js version: 14.2.3

@botgen/chat:build: Failed to compile.
@botgen/chat:build: 
@botgen/chat:build: node:stream
@botgen/chat:build: Module build failed: UnhandledSchemeError: Reading from "node:stream" is not handled by plugins (Unhandled scheme).
@botgen/chat:build: Webpack supports "data:" and "file:" URIs by default.
@botgen/chat:build: You may need an additional plugin to handle "node:" URIs.

@botgen/chat:build: Import trace for requested module:
@botgen/chat:build: node:stream
@botgen/chat:build: ../../node_modules/.pnpm/cohere-ai@7.10.0_encoding@0.1.13/node_modules/cohere-ai/core/form-data-utils/FormDataWrapper.js
@botgen/chat:build: ../../node_modules/.pnpm/cohere-ai@7.10.0_encoding@0.1.13/node_modules/cohere-ai/core/form-data-utils/index.js
@botgen/chat:build: ../../node_modules/.pnpm/cohere-ai@7.10.0_encoding@0.1.13/node_modules/cohere-ai/core/index.js
@botgen/chat:build: ../../node_modules/.pnpm/cohere-ai@7.10.0_encoding@0.1.13/node_modules/cohere-ai/Client.js
@botgen/chat:build: ../../node_modules/.pnpm/cohere-ai@7.10.0_encoding@0.1.13/node_modules/cohere-ai/index.js
@botgen/chat:build: ./lib/cohere.ts

Version 7.9.5 works OK.

**Comment by billytrend-cohere** [comment]
@dsinghvi i think the problem is here https://github.com/cohere-ai/cohere-typescript/blame/61db210693e173d12072626cedcfff0cc5e01e59/src/core/form-data-utils/FormDataWrapper.ts#L31

**Comment by billytrend-cohere** [comment]
hey @crtnx I just released 7.10.2 which should fix this issue! Let me know if you have any further problems
