### ISSUE TITLE
Can't resolve 'stream'

### ISSUE THREAD

**Issue by crtnx** [cohere-ai/cohere-typescript#164]
cohere-ai: 7.10.2
next.js: 14.2.3
node.js: 20.12.2

@botgen/chat:build: Module not found: Can't resolve 'stream'
@botgen/chat:build: 
@botgen/chat:build: https://nextjs.org/docs/messages/module-not-found
@botgen/chat:build: 
@botgen/chat:build: Import trace for requested module:
@botgen/chat:build: ../../node_modules/.pnpm/cohere-ai@7.10.2_@aws-sdk+client-sso-oidc@3.588.0_aws-crt@1.21.2__aws-crt@1.21.2_encoding@0.1.13/node_modules/cohere-ai/core/form-data-utils/index.js
@botgen/chat:build: ../../node_modules/.pnpm/cohere-ai@7.10.2_@aws-sdk+client-sso-oidc@3.588.0_aws-crt@1.21.2__aws-crt@1.21.2_encoding@0.1.13/node_modules/cohere-ai/core/index.js
@botgen/chat:build: ../../node_modules/.pnpm/cohere-ai@7.10.2_@aws-sdk+client-sso-oidc@3.588.0_aws-crt@1.21.2__aws-crt@1.21.2_encoding@0.1.13/node_modules/cohere-ai/Client.js
@botgen/chat:build: ../../node_modules/.pnpm/cohere-ai@7.10.2_@aws-sdk+client-sso-oidc@3.588.0_aws-crt@1.21.2__aws-crt@1.21.2_encoding@0.1.13/node_modules/cohere-ai/index.js
@botgen/chat:build: ./lib/cohere.ts

cohere-ai v7.9.5 works without problems

**Comment by fierysolid** [comment]
Easily fixed by installing the `stream` package, but this should probably be included in the package

**Comment by ystoneman** [comment]
+1

I had the same issue with `cohere-ai@7.10.2` and `Next.js 14.2.3`. Agree that the `stream` package should probably be included in the package.

**Comment by billytrend-cohere** [comment]
hey folks thanks for flagging this, will add stream to package as you suggest!

**Comment by ystoneman** [comment]
Thank you, @billytrend-cohere! When will the next release come out? I couldn't find a note about release schedule in the Readme. Thanks again for solving this issue!

**Comment by billytrend-cohere** [comment]
Released now!! please try 7.10.5 and let me know how it goes. I added a test case to prevent this situation happening in the future
