### ISSUE TITLE
Error when using rerank on AWS SageMaker

### ISSUE THREAD

**Issue by ianrutner-jasper** [cohere-ai/cohere-typescript#200]
I am trying to use `cohere-rerank-nimble-english-v3-02` via AWS SageMaker and cohere-typescript.

When making a request I get the following error
`Cannot read properties of undefined (reading 'parseOrThrow')`
which comes from here in `aws-utils.js`
```
const nonStreamedResponseParser = {
    "chat": serializers.NonStreamedChatResponse,
    "embed": serializers.EmbedResponse,
    "generate": serializers.Generation,
};
const mapResponseFromBedrock = (streaming, endpoint, obj) => __awaiter(void 0, void 0, void 0, function* () {
    const parser = streaming ? streamingResponseParser[endpoint] : nonStreamedResponseParser[endpoint];
    const config = {
        unrecognizedObjectKeys: "passthrough",
        allowUnrecognizedUnionMembers: true,
        allowUnrecognizedEnumValues: true,
        skipValidation: true,
        breadcrumbsPrefix: ["response"],
    };
    const parsed = yield parser.parseOrThrow(obj, config);
    return parser.jsonOrThrow(parsed, config);
});
```

The `endpoint` value is `rerank` and `nonStreamedResponseParser` does not have a `rerank` property so `parser` is undefined and throws when `yield parser.parseOrThrow(obj, config);` is called.

Is rerank via AWS SageMaker currently supposed to be supported?

Thanks!

**Comment by billytrend-cohere** [comment]
Hey @ianrutner-jasper thanks for reporting this, I'm investigating a fix for you!
