### ISSUE TITLE
User reports high CPU utilization

### ISSUE THREAD

**Issue by dannysheridan** [cohere-ai/cohere-typescript#211]
> **User report:**
> After debugging, we made requests directly using the Axios library, and things went smoothly.
> Unfortunately, I didn't record the errors, but I'll try my best to describe them in case it's helpful to your team:
> 
> cpu was unusually elevated when using the cohere sdk (v7.2.0) vs axios - pegged at 100% vs 20-30% with axios
> we also saw strange ssl connection timeout issues which would hang up requests unpredictably
> i believe we also had some issues with elevated memory

Originally filed on fern-api/fern as: https://github.com/fern-api/fern/issues/2918

**Comment by billytrend-cohere** [comment]
I think we can close this now, given that we have changed the http request library since then
