### ISSUE TITLE
Using "cohere-ai": "^5.0.2" in NodeJS, I'm getting an unexpected response from the classify endpoint

### ISSUE THREAD

**Issue by netpoe** [cohere-ai/cohere-typescript#70]
Using `"cohere-ai": "^5.0.2"` in NodeJS, I'm getting an unexpected response from the `classify` endpoint: 

```
{
  statusCode: 404,
  body: {
    message: "could not find preset by the ID of 60a0705a-5231-4d4a-b62f-...",
  },
}
```

I've tried several combinations (see attachments) to send the data by specifying a model, but I get typescript errors:

```
error TS2345: Argument of type '{ model: string; inputs: string[]; }' is not assignable to parameter of type 'classifyRequest'.
  Property 'preset' is missing in type '{ model: string; inputs: string[]; }' but required in type 'classifyWithPresetRequest'.
```

This is the data being sent:

```
{
  model: "60a0705a-5231-4d4a-b62f-...",
  inputs: [
    "crear wallet mxn",
  ],
  preset: "60a0705a-5231-4d4a-b62f-...",
}
```

By testing in https://docs.cohere.ai/reference/classify, I do get the expected results with almost the same args and the API Call even excludes `preset`.

<img width="665" alt="Screen Shot 2023-02-17 at 10 13 18" src="https://user-images.githubusercontent.com/4053518/219706876-efc19716-0c33-49d8-81cf-a8f48e62e71a.png">
<img width="570" alt="Screen Shot 2023-02-17 at 10 13 07" src="https://user-images.githubusercontent.com/4053518/219706879-ef192be0-33a4-4841-b7e9-21af307c219c.png">
<img width="527" alt="Screen Shot 2023-02-17 at 10 07 56" src="https://user-images.githubusercontent.com/4053518/219706882-aa183982-0884-42de-a483-092f610366e9.png">
<img width="462" alt="Screen Shot 2023-02-17 at 10 03 03" src="https://user-images.githubusercontent.com/4053518/219706883-23f1cf7d-f884-4c38-8c35-c846f929a1e0.png">
<img width="464" alt="Screen Shot 2023-02-17 at 10 01 47" src="https://user-images.githubusercontent.com/4053518/219706885-f764979c-4f92-410b-af74-4ae1b9513285.png">
<img width="928" alt="Screen Shot 2023-02-17 at 10 01 41" src="https://user-images.githubusercontent.com/4053518/219706888-3b4e12a3-9b5d-441b-87c5-76da879e27be.png">

**Comment by dsinghvi** [comment]
@netpoe The updated [ClassifyRequest](https://github.com/cohere-ai/cohere-typescript/blob/main/src/api/client/requests/ClassifyRequest.ts) now has an optional preset!
