### ISSUE TITLE
Module '"cohere-ai"' has no exported member 'CohereClient'

### ISSUE THREAD

**Issue by TephrosisDEV** [cohere-ai/cohere-typescript#98]
Hello,

I'm trying to use the chat functionality of Cohere.
I copied the example code, but I get this error:
**Module '"cohere-ai"' has no exported member 'CohereClient'.**
Is the example outdated? If so, what's the correct way to use the chatStream functionality?

When I check the file I only see these accessible functions:
- init
- generate
- tokenize
- detokenize
- embed
- classify
- detectLanguage
- summarize

```
import { CohereClient } from "cohere-ai";

const cohere = new CohereClient({
    token: process.env.COHERE_API_KEY || '',
});

(async () => {
    const stream = await cohere.chatStream({
        model: "command",
        message: "Tell me a story in 5 parts!",
    });

    for await (const chat of stream) {
        if (chat.eventType === "text-generation") {
            process.stdout.write(chat.text);
        }
    }
})();
```

**Comment by dsinghvi** [comment]
@TephrosisDEV I setup a working version of the SDK in [Stackblitz](https://stackblitz.com/edit/typescript-example-using-sdk-built-with-fern-jh8ecz?file=app.ts). You should be able to access `chatStream` and import `CohereClient`. 

Let me know if that works for you!

**Comment by TephrosisDEV** [comment]
That helped a lot.
I saw your version was 7.1.1, while mine was only 6.2.2
Now I have all autocomplete and experiment again.
Thanks a lot!
